on:
  pull_request:
    types: [opened, reopened, synchronize]

name: Deploy to Staging Environment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
      
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        
      - name: 'npm install and build'
        run: |
          npm install
          npm run build --if-present
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STAGING }}
      
      - name: Create Web App
        run: az webapp up -n hank-nextjs-pr${{ github.event.pull_request.number }} -p ASP-hank-spa-test-win2-b40f -g hank-spa-test-win
      
      - name: Set App Service Secrets
        run: az webapp config appsettings set -g hank-spa-test-win -n hank-nextjs-pr${{ github.event.pull_request.number }} --settings COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }} COSMOS_KEY=${{ secrets.COSMOS_KEY }} COSMOS_DATABASE=${{ secrets.COSMOS_DATABASE }} COSMOS_CONTAINER=${{ secrets.COSMOS_CONTAINER }}

      - name: az logout
        run: az logout