on:
  push:
    branches:
      - master

name: Deploy to Production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: 'npm install and build'
      run: |
        npm install
        npm run build --if-present
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set App Service Secrets
      run: |
        az webapp config appsettings set -g nextjs -n hank-nextjs --settings \
        COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }} \
        COSMOS_KEY=${{ secrets.COSMOS_KEY }} \
        COSMOS_DATABASE=${{ secrets.COSMOS_DATABASE }} \
        COSMOS_CONTAINER=${{ secrets.COSMOS_CONTAINER }}
    
    - uses: azure/webapps-deploy@v1
      with:
        app-name: 'hank-nextjs'
    
    - name: az logout
      run: az logout